### ISSUE TITLE
BUG 2 :查询条件未作URL编码导致数据异常

### ISSUE THREAD

**Issue by sinlee1** [tianmusec/SickleOfSkyCurtain#3]
-  未作URL编码的查询条件时，查询异常出现爆错：

![image](https://user-images.githubusercontent.com/29684167/132493856-1c8feb1b-e51c-40f1-a297-fe807ccac6a5.png)

- 做了URL编码的查询条件时，查询结果正常：

![image](https://user-images.githubusercontent.com/29684167/132494180-67473d55-67d8-4ddb-a2d0-dedbdf3fa9dd.png)

**Comment by tmusec** [comment]
已加
