### ISSUE TITLE
BUG 3 导出当前数据异常

### ISSUE THREAD

**Issue by sinlee1** [tianmusec/SickleOfSkyCurtain#4]
选择`导出当前数据`后，出现如下报错

![image](https://user-images.githubusercontent.com/29684167/132494658-6f6f59bf-f538-4e65-83fa-b53c35240ab3.png)

**Comment by tmusec** [comment]
复现失败

**Comment by sinlee1** [comment]
URL编码后语句：
`
app%3A%22Oracle%20WebLogic%20Server%22%20%2B%20country%3A%22US%22
`
点击导出后
![image](https://user-images.githubusercontent.com/29684167/133021621-612ed6f7-0a67-4a0c-9990-44a96b27e3eb.png)
