### ISSUE TITLE
导出当前数据异常-复现

### ISSUE THREAD

**Issue by sinlee1** [tianmusec/SickleOfSkyCurtain#6]
URL编码后语句：
`
app%3A%22Oracle%20WebLogic%20Server%22%20%2B%20country%3A%22US%22
`
点击导出后
![image](https://user-images.githubusercontent.com/29684167/133021621-612ed6f7-0a67-4a0c-9990-44a96b27e3eb.png)

最新版1.1导出依然是一样的问题
![image](https://user-images.githubusercontent.com/29684167/133022211-e9bc4e84-8981-4503-a151-362caaa4a70c.png)

**Comment by tmusec** [comment]
本地需安装office
